name: CI

on: 
  push:
    paths:
    - 'tests/**'
    - 'lib/**'
  pull_request:
    paths:
    - 'tests/**'
    - 'lib/**'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone nextcloud for test files
      uses: actions/checkout@v2
      with:
        repository: nextcloud/server
        path: nextcloud
        submodules: true
    - name: Install App
      uses: actions/checkout@v2
      with:
        path: nextcloud/apps/gadgetbridge
    - name: Configure Nextcloud & install composer
      run: |
        cd nextcloud
        composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
        php occ maintenance:install --admin-pass=admin
        php occ app:enable gadgetbridge
    - name: Install dependencies
      run: |
        cd nextcloud/apps/gadgetbridge
        composer install -q --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist
    - name: Run Tests      
      run: |
        cd nextcloud/apps/gadgetbridge
        phpunit
